### ISSUE TITLE
Vertex Shaders do not properly process Parameter 0

### ISSUE THREAD

**Issue by vivianlonging** [Ved-s/ShaderDecompiler#1]
Doing some testing to decompile a game's shaders, me and a few other modders for the game Celeste found that Parameter 0 is completely being ignored for the method definition of compiled VertexShaders, and that Parameter 1 is taking the role of both Parameter 0 and 1,
This could be a result of us using vs_2_0 which maybe has some different parametrization rules but I couldn't find any info anywhere to that effect.

Simplest recreation: 
We used a shader that we can be reasonable sure we know the contents of going it to diagnose the issue.
Taking Primitive.xnb and decompiling it results in the output sent in zip
[Primitive.zip](https://github.com/user-attachments/files/17008972/Primitive.zip)

**Comment by Ved-s** [comment]
Sorry, this project is abandoned. I'd like to see if someone forks it or rewrites it from scratch though.
